### ISSUE TITLE
message.acknowledge! early

### ISSUE THREAD

**Issue by mattes** [ursm/activejob-google_cloud_pubsub#5]
In the spirit of [how Rails handles exceptions in ActiveJobs](http://edgeguides.rubyonrails.org/active_job_basics.html#exceptions) I wonder if it might better to acknowledge a message right before the actual processing starts. Example:

```ruby
message.acknowledge!
ActiveJob::Base.execute JSON.parse(message.data)
```
https://github.com/ursm/activejob-google_cloud_pubsub/blob/master/lib/activejob-google_cloud_pubsub/worker.rb#L70-L105

That way it is up to the user what to do with exceptions using `retry_on` and `discard_on` hooks. 

After all I believe `acknowledge` should mean `delivered`, not `processed`.

**Comment by mattes** [comment]
This makes the `delay_timer` obsolete as well.

**Comment by ursm** [comment]
Since this library does not persist data of a job, if a worker terminates unexpectedly while executing a job, it will be lost without being executed forever. In order to prevent this problem, I implemented to `acknowledge` after the job succeeded or failed.

`delay_timer` is for different purposes. Cloud Pubsub will send the data again after assuming that the job has failed after up to 10 minutes have elapsed. Therefore, if it takes more time to execute the job, the same job will be executed at the same time. To prevent this, the worker periodically reschedules the job to Cloud Pubsub while the job is running.

 I would be happy if you let me know if I missed something.
